services:
  - type: web
    name: ltel-validador-win
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: RENDER
        value: "true"
      - key: NODE_ENV
        value: production
